describe("E2E testing", () => {
  it("tests E2E testing", () => {
    cy.viewport(1076, 791);
    cy.visit("http://localhost:5173/");
    cy.get("path").click();
    cy.get("a:nth-of-type(2) > button").click();
    cy.get("a:nth-of-type(3) > button").click();
    cy.get("a:nth-of-type(4) > button").click();
    cy.get("a:nth-of-type(5) > button").click();
    cy.get("a:nth-of-type(6) > button").click();
    cy.get("#email").click();
    cy.get("#email").type("A");
    cy.get("#email").type("Admin@gmail.com");
    cy.get("#password").click();
    cy.get("#password").type("A");
    cy.get("#password").type("Admin123");
    cy.get("#root > div > div button").click();
    cy.get("[data-testid='HomeIcon']").click();
    cy.get("a:nth-of-type(2) > button").click();
    cy.get("#«rg»").click();
    cy.get("#«rg»").type("Sin Yan");
    cy.get("#«rh»").type("Pang");
    cy.get("#«ri»").click();
    cy.get("#«ri»").type("ada.sy.pang@gmail.com");
    cy.get("#«rj»").click();
    cy.get("#«rj»").type("testing");
    cy.get("#«rk»").click();
    cy.get("#«rk»").type("2025-07-09");
    cy.get("#«rl»").click();
    cy.get("#«rl»").type("testing");
    cy.get("form button").click();
    cy.get("#").click();
    cy.get("#«rl»").click();
    cy.get("#«rl»").type("testing2");
    cy.get("form button").click();
    cy.get("#root > div > div > div > div:nth-of-type(2) button.MuiButton-textError").click();
    cy.get("a:nth-of-type(3) > button").click();
    cy.get("#«rr»").click();
    cy.get("#«rr»").type("Sin Yan");
    cy.get("#«rs»").type("Pang");
    cy.get("#«rt»").click();
    cy.get("#«rt»").type("ada.sy.pang@gmail.com");
    cy.get("#«ru»").click();
    cy.get("#«ru»").type("testing");
    cy.get("#«rv»").click();
    cy.get("#«rv»").type("2025-07-10");
    cy.get("#«r10»").click();
    cy.get("#«r10»").type("testing");
    cy.get("form > button").click();
    cy.get("div:nth-of-type(4) button.MuiButton-outlinedPrimary").click();
    cy.get("#«ru»").click();
    cy.get("#«ru»").type("testing2");
    cy.get("form > button").click();
    cy.get("div:nth-of-type(4) button.MuiButton-outlinedError").click();
    cy.get("a:nth-of-type(4) > button").click();
    cy.get("#«r1a»").click();
    cy.get("#«r1a»").type("Sin Yan");
    cy.get("#«r1b»").type("Pang");
    cy.get("#«r1c»").click();
    cy.get("#«r1c»").type("ada.sy.pang@gmail.com");
    cy.get("form button").click();
    cy.get("#root > div > div > div > div:nth-of-type(2) button.MuiButton-textPrimary").click();
    cy.get("#root > div > div").click();
    cy.get("#«r1a»").type("A");
    cy.get("#«r1a»").type("Ada");
    cy.get("form button").click();
    cy.get("#root > div > div > div > div:nth-of-type(2) button.MuiButton-textError").click();
    cy.get("a:nth-of-type(5) > button").click();
    cy.get("div.MuiStack-root > button").click();
    cy.get("a:nth-of-type(5) > button").click();
    cy.get("#name").click();
    cy.get("#name").type("User002");
    cy.get("#email").click();
    cy.get("#email").type("User002@gmail.com");
    cy.get("#password").click();
    cy.get("#password").type("U");
    cy.get("#password").type("User002");
    cy.get("#root > div > div button").click();
    cy.get("div.MuiDialog-root button").click();
    cy.get("#email").click();
    cy.get("#email").type("U");
    cy.get("#email").type("User002@gmail.com");
    cy.get("#password").click();
    cy.get("#password").type("U");
    cy.get("#password").type("User002");
    cy.get("#root > div > div button").click();
    cy.get("a:nth-of-type(2) > button").click();
    cy.get("a:nth-of-type(3) > button").click();
    cy.get("a:nth-of-type(4) > button").click();
    cy.get("a:nth-of-type(5) > button").click();
  });
});
//# recorderSourceMap=BCBDBEBFBGBHBIBJBKBLALALBMAMAMBNBOAOAOBPAPAPBQBRBSBTBUBVBWBXBYBZBaBbBcBdBeBfBgBBhBBiBBjBBkBBlBBmBBnBBoBBpBBqBBrBBsBBtBBuBBvBBwBBxBByBBzBB0BB1BB2BB3BB4BB5BB6BB7BB8BB9BB+BB/BA/BA/BBgCAgCAgCBhCBiCBjCBkCBlCBmCBnCBoCBpCBqCBrCArCArCBsCAsCAsCBtCBuCBvCBwCAwCAwCBxCAxCAxCByCBzCAzCAzCB0CA0CA0CB1CB2CB3CB4CB5CB
