describe("portfolio", () => {
  it("tests portfolio", () => {
    cy.viewport(981, 791);
    cy.visit("http://localhost:5173/");
    cy.get("a:nth-of-type(2) > button").click();
    cy.get("a:nth-of-type(3) > button").click();
    cy.get("a:nth-of-type(4) > button").click();
    cy.get("a:nth-of-type(5) > button").click();
    cy.get("#name").click();
    cy.get("#name").type("U");
    cy.get("#name").type("User002");
    cy.get("#email").click();
    cy.get("#email").type("U");
    cy.get("#email").type("User002@gmail.com");
    cy.get("#password").click();
    cy.get("#password").type("U");
    cy.get("#password").type("User002");
    cy.get("#root > div > div button").click();
    cy.get("div.MuiDialog-root button").click();
    cy.get("#email").click();
    cy.get("#email").type("U");
    cy.get("#email").type("User002@gmail.com");
    cy.get("#password").click();
    cy.get("#password").type("U");
    cy.get("#password").type("User002");
    cy.get("#root > div > div button").click();
    cy.get("a:nth-of-type(2) > button").click();
    cy.get("a:nth-of-type(3) > button").click();
    cy.get("a:nth-of-type(4) > button").click();
    cy.get("a:nth-of-type(5) > button").click();
    cy.get("[data-testid='EditIcon']").click();
    cy.get("#name").click();
    cy.get("#name").type("User003");
    cy.get("#root > div > div button").click();
    cy.get("[data-testid='DeleteIcon']").click();
    cy.get("button.MuiButton-contained").click();
    cy.get("a:nth-of-type(6) > button").click();
    cy.get("#email").click();
    cy.get("#email").type("Admin@gmail.com");
    cy.get("#password").click();
    cy.get("#password").type("A");
    cy.get("#password").type("Admin123");
    cy.get("#root > div > div button").click();
    cy.get("a:nth-of-type(2) > button").click();
    cy.get("#«r14»").click();
    cy.get("#«r14»").type("Sin Yan");
    cy.get("#«r15»").type("Pang");
    cy.get("#«r16»").click();
    cy.get("#«r16»").type("ada.sy.pang@gmail.com");
    cy.get("#«r17»").click();
    cy.get("#«r17»").type("testing");
    cy.get("#«r18»").click();
    cy.get("#«r18»").click();
    cy.get("#«r18»").click();
    cy.get("#«r18»").type("2025-07-22");
    cy.get("#«r19»").click();
    cy.get("#«r19»").type("testing");
    cy.get("form button").click();
    cy.get("#root > div > div > div > div:nth-of-type(2) button.MuiButton-textPrimary").click();
    cy.get("#«r19»").click();
    cy.get("#«r19»").type("testing2");
    cy.get("form button").click();
    cy.get("#root > div > div > div > div:nth-of-type(2) button.MuiButton-textError").click();
    cy.get("a:nth-of-type(3) > button").click();
    cy.get("#«r1f»").click();
    cy.get("#«r1f»").type("Sin Yan");
    cy.get("#«r1g»").type("Pang");
    cy.get("#«r1h»").click();
    cy.get("#«r1h»").type("ada.sy.pang@gmail.com");
    cy.get("#«r1i»").click();
    cy.get("#«r1i»").type("testing");
    cy.get("#«r1j»").click();
    cy.get("#«r1j»").click();
    cy.get("#«r1j»").type("2025-07-17");
    cy.get("#«r1k»").click();
    cy.get("#«r1k»").type("testing");
    cy.get("form > button").click();
    cy.get("div:nth-of-type(4) button.MuiButton-outlinedPrimary").click();
    cy.get("div:nth-of-type(4) button.MuiButton-outlinedPrimary").click();
    cy.get("#«r1k»").click();
    cy.get("#«r1k»").type("testing2");
    cy.get("form > button").click();
    cy.get("div:nth-of-type(4) button.MuiButton-outlinedError").click();
    cy.get("a:nth-of-type(4) > button").click();
    cy.get("#«r1u»").click();
    cy.get("#«r1u»").type("Sin Yan");
    cy.get("#«r1v»").type("Pang");
    cy.get("#«r20»").click();
    cy.get("#«r20»").type("testing");
    cy.get("form button").click();
    cy.get("#«r20»").click();
    cy.get("#«r20»").type("testing@gmail.com");
    cy.get("form button").click();
    cy.get("#root > div > div > div > div:nth-of-type(2) button.MuiButton-textPrimary").click();
    cy.get("#«r20»").click();
    cy.get("#«r20»").type("testing2@gmail.com");
    cy.get("form button").click();
    cy.get("#root > div > div > div > div:nth-of-type(2) button.MuiButton-textError").click();
    cy.get("a:nth-of-type(5) > button").click();
    cy.get("div.MuiStack-root > button").click();
  });
});
//# recorderSourceMap=BCBDBEBFBGBHBIBJAJAJBKAKAKBLBMAMAMBNANANBOBPAPAPBQAQAQBRBSBTBUAUAUBVAVAVBWBXAXAXBYAYAYBZBaBbBcBdBeBfBgBBhBBiBBjBBkBBlBBmBBnBBoBAoBAoBBpBApBApBBqBBrBBsBBtBBuBBvBBwBBxBByBBzBB0BB1BB2BB3BB4BB5BB6BB7BB8BB9BB+BB/BBgCBhCBiCBjCBkCBlCBmCBnCBoCBpCBqCBrCBsCBtCBuCBvCBwCBxCByCBzCB0CB1CB2CB3CB4CB5CB6CB7CB8CB9CB+CB/CBgDBhDBiDBjDB
